fix issues #53 and #61
muon-protocol/muon-node-js pull request #143
Opened 2023-06-08 04:31 UTC by fofaraz

2023-06-08 08:38 UTC, bakhshandeh reviewed
Let's move `DISCOVERY_VALID_TIMESTAMP` to net.default.conf and set a 30 secs default for it.

`discovery_acceptable_delay`

2023-06-08 08:43 UTC, bakhshandeh requested changes
rename the route to `/ifconfig` as we mentioned on the issue. 
Its more geeky and professional.

2023-06-08 08:46 UTC, bakhshandeh requested changes
As we discussed the user should be able to set `PUBLIC_IP` in .env
If PUBLIC_IP is on the config, there is no need to call /ifconfig and get the ip.

2023-06-09 06:35 UTC, fofaraz commented
changes applied
please review

2023-06-09 09:38 UTC, fofaraz commented on src/utils/helpers.ts
test

2023-06-09 11:24 UTC, fofaraz commented on src/utils/helpers.ts
> +   let ip = await Promise.any([
This creates an issue. When running a devnet node on local machine, there are no other nodes on loca to call /ifconfig on them so ifconfig request fails.
in this case we can use defined PUBLIC_IP in .env 
Do we need to anything else for it?

2023-06-09 12:03 UTC, fofaraz commented
Updated. Please review.

2023-06-12 08:42 UTC, merged